// Charging stations data for HCMC extracted from CSV
// Coordinates are approximate based on district/neighborhood information
// Format: latitude, longitude (HCMC center is approximately 10.7769, 106.7009)

export interface ChargingStation {
  id: number;
  name: string;
  address: string;
  district: string;
  ports: string;
  latitude: number;
  longitude: number;
  mapX: number; // Percentage from left (0-100)
  mapY: number; // Percentage from top (0-100)
}

// HCMC district coordinate boundaries (approximate percentages on map)
// Left: 106.38, Right: 107.02, Top: 10.99, Bottom: 10.50
const HCMC_BOUNDS = {
  minLat: 10.50,
  maxLat: 10.99,
  minLng: 106.38,
  maxLng: 107.02,
};

const latToY = (lat: number): number => {
  return ((HCMC_BOUNDS.maxLat - lat) / (HCMC_BOUNDS.maxLat - HCMC_BOUNDS.minLat)) * 100;
};

const lngToX = (lng: number): number => {
  return ((lng - HCMC_BOUNDS.minLng) / (HCMC_BOUNDS.maxLng - HCMC_BOUNDS.minLng)) * 100;
};


  // Quận 3
  export const quan3Stations = [
  {
    id: 1,
    name: "Chung cư Léman Luxury",
    address: "Tầng hầm B3, Tòa nhà Léman Luxury Apartments, 117 Nguyễn Đình Chiểu, phường 6, Quận 3, Thành phố Hồ Chí Minh.",
    district: "Quận 3",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Bãi đỗ xe La Vela Saigon Hotel",
    address: "Số 280, đường Nam Kỳ Khởi Nghĩa, Phường Võ Thị Sáu, Quận 3, Thành phố Hồ Chí Minh.",
    district: "Quận 3",
    ports: "02 cổng sạc 150Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Tổng công ty Đường sắt Việt Nam - Ga Sài Gòn",
    address: "Quận 3, Thành phố Trung ương Hồ Chí Minh",
    district: "Quận 3",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
  // Quận 4
 export const quan4Stations = [
  {
    id: 1,
    name: "VIN3SSG Quận 4",
    address: "217A Bến Vân Đồn, Phường 2, Quận 4, TP. Hồ Chí Minh",
    district: "Quận 4",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
  // Quận 5
  export const quan5Stations = [
  {
    id: 1,
    name: "Trung tâm Hội nghị The Adora Grand View",
    address: "Số 421, đường Ngô Gia Tự, Phường 9, Quận 5, TP. Hồ Chí Minh",
    district: "Quận 5",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
  // Quận 6
  export const quan6Stations = [
  {
    id: 1,
    name: "Bãi đỗ xe Huỳnh Hiếu Thiện (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 130/30G, đường Nguyễn Văn Luông, Phường 10, Quận 6, TP. Hồ Chí Minh",
    district: "Quận 6",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Chung cư Summer Square",
    address: "Hầm B1, Chung cư Summer Square, Số 243, đường Tân Hòa Đông, phường 14, Quận 6, TP. Hồ Chí Minh",
    district: "Quận 6",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
  // Quận 7
export const quan7Stations = [
  {
    id: 1,
    name: "Chung cư Eco Green HR1",
    address: "Tòa nhà HR1, Eco Green, Khu dân cư Tân Thuận Tây, Số 107, Đường Nguyễn Văn Linh, Phường Tân Thuận Tây, Quận 7, Thành phố Hồ Chí Minh",
    district: "Quận 7",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Chung cư Eco Green HR2",
    address: "Tòa nhà HR2, Eco Green, Khu dân cư Tân Thuận Tây, số 107, đường Nguyễn Văn Linh, Phường Tân Thuận Tây, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Đại lý Ô tô VinFast, Chevrolet Phú Mỹ Hưng 2",
    address: "Số 54, đường Nguyễn Thị Thập, phường Bình Thuận, Quận 7, Thành phố Hồ Chí Minh",
    district: "Quận 7",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Trung tâm Hội nghị The Adora Premium",
    address: "Số 803, Đường Nguyễn Văn Linh, Phường Tân Phú, Quận 7, Thành phố Hồ Chí Minh",
    district: "Quận 7",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Chung cư Golden King",
    address: "Tầng hầm B2, tòa nhà Golden King, số 15, đường Nguyễn Lương Bằng, phường Tân Phú, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "02 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "Chung cư Green View",
    address: "Đường Nguyễn Lương Bằng, phường Tân Phú, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Chung cư Cảnh Viên 1",
    address: "Khu Phố Cảnh Viên, Phường Tân Phú, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "Bãi đỗ xe Cty TyreZone",
    address: "Số 90/2, Đường Hoàng Quốc Việt, Phường Phú Mỹ, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "06 cổng sạc 11Kw, 08 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "Bãi đỗ xe tư nhân Phú Mỹ",
    address: "Đường số 1, Phường Phú Mỹ, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 10,
    name: "Bãi đỗ xe Cầu Phú Xuân",
    address: "Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 11,
    name: "Nhượng quyền Luxury - Công ty Ninh Bình",
    address: "Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 12,
    name: "Bãi đỗ xe tư nhân Gò Ô Môi",
    address: "Số 202, Gò Ô Môi, Khu phố 2, Phường Phú Thuận, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 13,
    name: "Bãi đỗ xe tư nhân Phú Nhuận",
    address: "Đường Gò Ô Môi, Phường Phú Thuận, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "01 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 14,
    name: "Nhượng quyền TXTX - Phạm Nguyễn Ngọc Ánh",
    address: "E31 Khu Nam Long.Phường Phú Thuận Q7, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "01 cổng sạc 22Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 15,
    name: "Vincom+ Nam Long",
    address: "Số 71, đường Trần Trọng Cung, phường Tân Thuận Đông, Quận 7, Thành phố Hồ Chí Minh.",
    district: "Quận 7",
    ports: "01 cổng sạc 22Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
  // Quận 8
export const quan8Stations = [
  {
    id: 1,
    name: "Bãi đỗ xe Tạ Quang Bửu",
    address: "Bãi Đỗ xe Ngoài trời, Ngã 3 Võ Liêm Sơn với Tạ Quang Bửu, phường 4, Quận 8, Thành phố Hồ Chí Minh.",
    district: "Quận 8",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Bãi đỗ xe tư nhân Trịnh Quang Nghị",
    address: "Số 41, Đường Trịnh Quang Nghị, Khu phố 5, Phường 07, Quận 8, Thành phố Hồ Chí Minh.",
    district: "Quận 8",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Bãi đỗ xe tư nhân Võ Văn Kiệt",
    address: "Số 204/169, Đường An Dương Vương, Phường 16, Quận 8, Thành phố Trung ương Hồ Chí Minh",
    district: "Quận 8",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Nhượng quyền TXTX - Phạm Duy Hoàn",
    address: "95A Dương Bá Trạc, P.1, Quận 8, Thành phố Trung ương Hồ Chí Minh",
    district: "Quận 8",
    ports: "01 cổng sạc 22Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Bãi đỗ xe Tư nhân - Phường 7, Quận 8",
    address: "Thửa đất số 546, tờ bản đồ số 12, địa chỉ thửa đất: Phường 7, Quận 8, Thành phố Hồ Chí Minh.",
    district: "Quận 8",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "NQ Tư Nhân CAFÉ A LINH",
    address: "Số 142 Rạch Cát Bến Lức, Phường 07, Quận 8, Thành Phố Hồ Chí Minh, Quận 8, Thành phố Hồ Chí Minh.",
    district: "Quận 8",
    ports: "01 cổng sạc 22Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Nhượng quyền Luxury - Hộ kinh doanh Châu Thắng",
    address: "136 Hoàng Ngân ,phường 16 Quận 8, TP Hồ Chí Minh, Quận 8, Thành phố Hồ Chí Minh",
    district: "Quận 8",
    ports: "04 cổng sạc 60Kw, 04 cổng sạc 120Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "NQ Platform - Lưu Thanh Đạt",
    address: "Số 29/2, Đường Bình Đông, Phường 15, Quận 8, Thành phố Hồ Chí Minh",
    district: "Quận 8",
    ports: "01 cổng sạc 22Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "NQ TXTX Đinh Triệu Hùng",
    address: "60 Lương Ngọc Quyến, phường 13, Quận 8, Thành Phố Hồ Chí Minh, Quận 8, Thành phố Hồ Chí Minh",
    district: "Quận 8",
    ports: "01 cổng sạc 7.4Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 10,
    name: "NQ LUX Phạm Đăng Khoa",
    address: "1107/72 Phạm Thế Hiển, P.5, Quận 8, Thành phố Hồ Chí Minh.",
    district: "Quận 8",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
  // Quận 10
export const quan10Stations = [
  {
    id: 1,
    name: "VinFast Ba Tháng Hai",
    address: "Tầng 1, TTTM Vincom Plaza Ba Tháng Hai, 3C Đường 3 Tháng 2, P.11, Quận 10, TP. Hồ Chí Minh",
    district: "Quận 10",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
  // Quận 11
export const quan11Stations = [
  {
    id: 1,
    name: "Bãi đỗ xe Hòa Bình Đầm Sen (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 22/13, Đường Hòa Bình, Phường 05, Quận 11, TP. Hồ Chí Minh",
    district: "Quận 11",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
  // Quận 12
export const quan12Stations = [
  {
    id: 1,
    name: "Bãi đỗ xe Tâm Phúc",
    address: "Số 885/12, Đường Nguyễn Ảnh Thủ, Phường Tân Chánh Hiệp, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "04 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Bãi đỗ xe tư nhân Thùy Trang",
    address: "Số 8/4, Khu Phố 3, phường Tân Chánh Hiệp, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "01 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Bãi đỗ xe Tân Thới Hiệp",
    address: "Phường Tân Thới Hiệp, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Bãi đỗ xe S778 Nguyễn Văn Quá",
    address: "Số 778, đường Nguyễn Văn Quá, phường Đông Hưng Thuận, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "01 cổng sạc 11Kw, 01 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Bãi đỗ xe Diệu Phát",
    address: "Số 662/7 Lê Văn Khương, Phường Thới An, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "Trạm trung chuyển Thới An",
    address: "Số 59/1, đường Lê Thị Riêng, Khu phố 3, phường Thới An, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Bãi đỗ xe Chung cư Hiệp Thành",
    address: "Số 387A, đường Lê Văn Khương, Khu phố 2, phường Hiệp Thành, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "02 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "Bãi đỗ xe Minh Phúc",
    address: "34/5 đường Tỉnh lộ 56, Khu phố 2, phường Thạnh Lộc, Quận 12, Thành phố Hồ Chí Minh",
    district: "Quận 12",
    ports: "03 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "Bãi đỗ xe 24E – Thạnh Xuân",
    address: "Số 24E, tổ 26, khu phố 2, phường Thạnh Xuân, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "05 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 10,
    name: "Bãi đỗ xe tư nhân Anh Nam 2",
    address: "Số 48, Đường tỉnh lộ 40, Khu phố 1, Phường Thạnh Lộc, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 11,
    name: "Bãi đỗ xe Bờm Auto",
    address: "Số 79, Đường Thạnh Xuân 21, phường Thạnh Xuân, Quận 12, Thành phố Hồ Chí Minh",
    district: "Quận 12",
    ports: "03 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 12,
    name: "Bãi đỗ xe tư nhân Tô Ngọc Vân",
    address: "90/3 Tô Ngọc Vân, Khu phố 5, Phường Thạnh Xuân, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 13,
    name: "Bãi đỗ xe 437 Hà Huy Giáp",
    address: "Số 437, Đường Hà Huy Giáp, Phường Thạnh Xuân, Quận 12, Thành phố Hồ Chí Minh",
    district: "Quận 12",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 14,
    name: "Bãi đỗ xe DBK",
    address: "Số 96, Khu phố 3, Phường thanh Lộc, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "03 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 15,
    name: "Bãi đỗ xe tư nhân Số 08",
    address: "Phường Thạnh Lộc, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "04 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 16,
    name: "Bãi đỗ xe An Phú Đông",
    address: "101 Nguyễn Thị Nhuần Phường An Phú Đông, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "04 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 17,
    name: "Bãi đỗ xe Auto Phúc Nguyên",
    address: "Số 94/117, đường An Phú Đông 09, phường An Phú Đông, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 18,
    name: "Bãi đỗ xe tư nhân Ân An",
    address: "Số 65, Đường Nguyễn Thị Nhuần, Khu phố 1, Phường An Phú Đông, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 19,
    name: "Bãi đỗ xe Thu Hiền",
    address: "Hẻm 92/14 Vườn Lài, Phường An Phú Đông, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 20,
    name: "Bãi đỗ xe Anh Sơn 6",
    address: "Số 242, đường Vườn Lài, Khu phố 2, Phường An Phú Đông, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 21,
    name: "Bãi đỗ xe 24H - 331 Vườn Lài",
    address: "Số 331/26, Đường Vườn Lài, Tổ 25, Khu phố 2, Phường An Phú Đông, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 22,
    name: "Bãi đỗ xe FamilyCar",
    address: "Số 1368 Vườn Lài, Phường An Phú Đông, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 23,
    name: "Bãi đỗ xe tư nhân C3",
    address: "Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 24,
    name: "Bãi đỗ xe tư nhân Huỳnh Thị Hai",
    address: "Số 280, Đường Huỳnh Thị Hai, Khu phố 8, Phường Tân Chánh Hiệp, Quận 12, Thành phố Hồ Chí Minh.",
    district: "Quận 12",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 25,
    name: "MM Mega Market Hiệp Phú",
    address: "2 Đ.Trương Thị Hoa, Tân Thới Hiệp, Quận 12, Hồ Chí Minh.",
    district: "Quận 12",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 26,
    name: "Cửa hàng xăng dầu SFC Số 20",
    address: "VJHX+PH5, Lê Văn Khương, Thới An, Quận 12, Hồ Chí Minh.",
    district: "Quận 12",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
  // Huyện Nhà Bè
  // Huyện Hóc Môn
  // Huyện Củ Chi
  // Huyện Cần Giờ
  // Huyện Bình Chánh
export const huyenNhaBeStations = [
  {
    id: 1,
    name: "Bãi đỗ xe Trường Tín",
    address: "Số 748, Đường Nguyễn Văn Tạo, Xã Hiệp Phước, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "01 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Bãi đỗ xe tư nhân Anh Bình",
    address: "Xã Long Thới, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Cửa hàng xăng dầu Mipec Anh Huy",
    address: "Cửa hàng xăng dầu Mipec Anh Huy, 453 ấp 2 Nguyễn Văn Tạo, xã Long Thới, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Bãi đỗ xe tư nhân Chị Diễm 4",
    address: "Số 2009/35, Đường Lê Văn Lương, Xã Nhơn Đức, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "05 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Cửa hàng xăng dầu Thuận Khải",
    address: "Số 749, Đường Lê Văn Lương, Tổ 4, ấp 3, Xã Nhơn Đức, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "Bãi đỗ xe tư nhân Lê Văn Lương",
    address: "Xã Nhơn Đức, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "09 cổng sạc 11Kw, 16 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Gara Anh Mạnh",
    address: "Lô C4/2, Khu dân cư Phú Xuân, xã Phú Xuân, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "01 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "Bãi đỗ xe tư nhân 288A Phạm Hữu Lầu",
    address: "Số 288A, đường Phạm Hữu Lầu, Ấp 4, xã Phước Kiển, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "Bãi đỗ xe Thanh Phong Auto Nhà Bè",
    address: "Số 1260 Lê Văn Lương, xã Phước Kiển, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 10,
    name: "Bãi đỗ xe CT - Khu C Phước Kiển",
    address: "Ấp 3, xã Phước Kiển, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 11,
    name: "Chung cư HAGL Gold House A",
    address: "Số 187A Lê Văn Lương, xã Phước Kiểng, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 12,
    name: "Chung cư HAGL Gold House B",
    address: "Số 187A Lê Văn Lương, xã Phước Kiểng, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 13,
    name: "Nhượng quyền VIP - Tư nhân Nguyễn Thiện Tuấn",
    address: "Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 14,
    name: "Bãi đỗ xe tư nhân Phạm Hữu Lầu",
    address: "Số 310, Đường Phạm Hữu Lầu, Ấp 4, Xã Phước Kiển, Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "03 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 15,
    name: "Nhượng quyền - Văn phòng Phú Long - Dragon Hill",
    address: "Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 16,
    name: "Nhượng quyền - Văn phòng PV Gas Tower - Nguyễn Hữu Thọ",
    address: "Huyện Nhà Bè, Thành phố Hồ Chí Minh.",
    district: "Huyện Nhà Bè",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];

  export const huyenHocMonStations = [
  {
    id: 1,
    name: "Cửa hàng xăng dầu Tài Lộc Thinh 5",
    address: "Xã Xuân Thới Sơn, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 180Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Bãi đỗ xe Chú Minh",
    address: "Xã Tân Thới Nhì, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Bãi đỗ xe Trần Anh",
    address: "Xã Tân Hiệp, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Bãi đỗ xe 15 Huỳnh Thị Mài",
    address: "15 Đường Huỳnh Thị Mài, xã Tân Hiệp, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "01 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Bãi đỗ xe Trần Anh 3",
    address: "Số 1/1H, đường Thới Tây 1, Xã Tân Hiệp, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "Bãi đỗ xe Đô Rê Mon",
    address: "284 Lê Thị Lơ, Ấp Thới Tây 2, xã Tân Hiệp, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "03 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Bãi đỗ xe tư nhân 108 Đường Song Hành",
    address: "Số 108, Đường Song Hành, xã Tân Hiệp, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "01 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "Bãi đỗ xe Tân Thới Nhì 2",
    address: "Đường Tân Thới Nhì 2, Xã Tân Thới Nhì, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "05 cổng sạc 11Kw, 12 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "Bãi đỗ xe Tân Hiệp 18A",
    address: "Số 12F 112 Tân Hiệp 18A, xã Tân Hiệp, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 10,
    name: "Bãi đỗ xe tư nhân - 36/7A Ấp Trung Đông 2",
    address: "Số 36/7A, tổ 76, ấp Trung Đông 2, xã Thới Tam Thôn, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "03 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 11,
    name: "Bãi đỗ xe tư nhân Tuyết Mai",
    address: "7K Ấp 5, xã Xuân Thới Thượng, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 08 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 12,
    name: "Bãi đỗ xe Nguyễn Văn Bứa",
    address: "Số 34, Đường Nguyễn Văn Bứa, Xã Xuân Thới Sơn, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "08 cổng sạc 11Kw, 16 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 13,
    name: "Bãi đỗ xe Năm Phát II",
    address: "Đường Nguyễn Thị Thử, xã Xuân Thới Sơn, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "01 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 14,
    name: "Bãi đỗ xe 41/1 Xuân Thới Thượng",
    address: "Số 41/1, Ấp 3, xã Xuân Thới Thượng, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 15,
    name: "Bãi đỗ xe Gara Trung Chánh",
    address: "Số 1/33B Ấp Đình, xã Tân Xuân, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "01 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 16,
    name: "Bãi đỗ xe Anh Quốc",
    address: "Số 679 đường Trung Mỹ, Tân Xuân, ấp Đình, xã Tân Xuân, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "01 cổng sạc 11Kw, 01 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 17,
    name: "Bãi đỗ xe Phong Khanh",
    address: "Số 555, đường Trung Mỹ, Xã Tân Xuân, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 18,
    name: "Bãi đỗ xe Phương Trang",
    address: "Số 487/28, đường Tô ký 12, Ấp Nam Thới, Xã Thới Tam Thôn, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "07 cổng sạc 11Kw, 10 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 19,
    name: "Bãi đỗ xe tư nhân Phạm Thành Việt",
    address: "Thới Tam Thôn, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 20,
    name: "Bãi đỗ xe LUX 99",
    address: "Số 99A, đường Phạm Thị Giây, Ấp Tam Đông 2, xã Thới Tam Thôn, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 21,
    name: "Bãi đỗ xe Đông Nam",
    address: "Số 347 đường Song Hành quốc lộ 22, ấp Mỹ Hòa 3, xã Tân Xuân, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 22,
    name: "Bãi đỗ xe Nguyễn Ảnh Thủ",
    address: "Số 86/2, Ấp Trung Mỹ Tây, Xã Tân Xuân, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 23,
    name: "Bãi đỗ xe tư nhân Chị Diễm 3",
    address: "Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 24,
    name: "Bãi đỗ xe tư nhân Chú Tám",
    address: "Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "01 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 25,
    name: "Bãi đỗ xe YOGA Ngọc Nguyên",
    address: "3/45 B Nguyễn Thị Điệp, ấp 1, xã Đông Thạnh, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 26,
    name: "Bãi đỗ xe 380 Huỳnh Thị Na",
    address: "Số 380, đường Huỳnh Thị Na, xã Đông Thạnh, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "05 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 27,
    name: "Bãi đỗ xe Thuỳ Trâm",
    address: "Số 35M, Đường Lê Văn Khương, xã Đông Thạnh,, Huyện Hóc Môn, Thành phố Trung ương Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "05 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 28,
    name: "Bãi đỗ xe Nhị Bình 04 - Số 330/05/04 Ấp 1",
    address: "Số 330/05/04, Ấp 1, xã Nhị Bình, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 29,
    name: "Bãi đỗ xe tư nhân Nhị Bình 08",
    address: "Đường Nhị Bình 8, Xã Nhị Bình, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 30,
    name: "Bãi đỗ xe Nhị Bình 15 - Số 319 Nhị Bình",
    address: "Số 319 Nhị Bình 15, xã Nhị Bình, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 31,
    name: "Bãi đỗ xe tư nhân Cường Thảo II",
    address: "Số 299, Đường Nhị Bình 15, Ấp 2, Xã Nhị Bình, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "06 cổng sạc 11Kw, 12 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 32,
    name: "Bãi đỗ xe Cà Phê Gia Long",
    address: "Số 7, đường Nhị Bình 16, xã Nhị Bình, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 33,
    name: "Bãi đỗ xe tư nhân Chị Diễm 2",
    address: "Số 30/25, Ấp 3, Xã Nhị Bình, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 11Kw, 08 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 34,
    name: "Bãi đỗ xe tư nhân TK12 Bà Điểm",
    address: "Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "03 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 35,
    name: "Bãi đỗ xe tư nhân Anh Huy",
    address: "Số 1696/5, Đường Nguyễn Ánh Thủ, Ấp Hưng Lân, Xã Bà Điểm, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 22Kw, 08 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 36,
    name: "Bãi đỗ xe tư nhân Việt Nam Logistics",
    address: "Đường Xuân Thới 3, Xã Xuân Thới Đông, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "01 cổng sạc 22Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 37,
    name: "Bãi đỗ xe tư nhân Tân Xuân 2",
    address: "ấp Xuân Thới Đông 1, xã Tân Xuân, Xuân Thới Đông, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 22Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 38,
    name: "Bãi đỗ xe Anh Thả",
    address: "Xã Xuân Thới Sơn, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 39,
    name: "Bãi đỗ xe tư nhân Tân Xuân",
    address: "Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 40,
    name: "Nhượng quyền VIP - Tư nhân Nguyễn Sỹ Tú",
    address: "Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 41,
    name: "Bãi đỗ xe Công ty Vận tải du lịch Tường Băng",
    address: "Xã Đông Thạnh, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 42,
    name: "Nhượng quyền Luxury - Trần Thêm Vinh",
    address: "Huyện Hóc Môn, Thành phố Hồ Chí Minh",
    district: "Huyện Hóc Môn",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 43,
    name: "Bãi đỗ xe Bùi Công Trừng",
    address: "Xã Nhị Bình, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 44,
    name: "Bãi đỗ xe tư nhân Tân Hiệp 32",
    address: "Xã Tân Hiệp, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "02 cổng sạc 11Kw, 06 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 45,
    name: "Trung tâm sát hạch lái xe Hóc Môn",
    address: "số 2244/10 Quốc lộ 22, Ấp Tân Thới 3, Xã Tân Hiệp, Huyện Hóc Môn, Thành phố Hồ Chí Minh.",
    district: "Huyện Hóc Môn",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];

export const huyenCuChiStations = [
  {
    id: 1,
    name: "Bãi đỗ xe Link VN Thái Mỹ (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 480, Tỉnh Lộ 7, Xã Thái Mỹ, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Cửa hàng xăng dầu Petrolimex Hồ Chí Minh Số 60 (Dự kiến hoạt động từ 28/10/2023)",
    address: "Số 21, Tỉnh lộ 8, Ấp Tam Tân, xã Tân An Hội, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Cửa hàng xăng dầu Tài Lộc Thinh 4",
    address: "Số 281, Quốc lộ 22, Xã Phước Hiệp, Củ Chi, HCM, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "02 cổng sạc 180Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Bãi đỗ xe Café Pen Tea (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 529, Tỉnh Lộ 2, Xã Trung Lập Hạ, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Bãi đỗ xe 54 Đặng Thị Tô (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 54, Đường Đặng Thị Tô, Phường Trung Lập Hạ, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "Cửa hàng xăng dầu Petrolimex Hồ Chí Minh Số 65 (Dự kiến hoạt động từ 28/10/2023)",
    address: "Số 955, đường Nguyễn Thị Rành, ấp Xóm Mới, xã An Nhơn Tây, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Bãi đỗ xe LTN Trọng Đức (Dự kiến hoạt động từ 31/12/2023)",
    address: "Đường Đỗ Đăng Tuyển, xã Nhuận Đức, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "Bãi đỗ xe Tư nhân Nguyễn Mỹ Trang (Dự kiến hoạt động từ 09/10/2023)",
    address: "Đường Nguyễn Thị Rành, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "Bãi đỗ xe Tỉnh Lộ 2 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Tổ 4, Ấp Trảng Lắm, Xã Trung Lập Hạ, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 12,
    name: "Bãi đỗ xe Gara Ô tô Trung Kiên (Dự kiến hoạt động từ 30/12/2023)",
    address: "Tỉnh lộ 8, Xã Phước Vĩnh An, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 13,
    name: "Cửa hàng xăng dầu Tài Lộc 16 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 400, Quốc Lộ 22, Ấp Tân Lập, Xã Tân Thông Hội, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 14,
    name: "Bãi đỗ xe tư nhân Chú Mưa (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 602, Quốc Lộ 22, Thị Trấn Củ Chi, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 15,
    name: "Bãi đỗ xe 54 Nguyễn Viết Xuân (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 54, Đường Nguyễn Viết Xuân, Thị trấn Củ Chi, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 16,
    name: "Bãi đỗ xe tư nhân Minh Nhật (Dự kiến hoạt động từ 31/12/2023)",
    address: "Ấp Giồng Sao, Xã Tân Phú Trung, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 17,
    name: "Bãi đỗ xe Cơm Niêu Bàu Đá (Dự kiến hoạt động từ 31/12/2023)",
    address: "Xã Tân Phú Trung, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 18,
    name: "Bãi đỗ xe Võ Liên (Dự kiến hoạt động từ 31/12/2023)",
    address: "Đường Số 64, Xã Tân Phú Trung, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 19,
    name: "Cửa hàng xăng dầu PVOIL Số 1, Sài Gòn",
    address: "Số 329, tổ 7, đường Hồ Văn Tắng, ấp Cây Da, xã Tân Phú Trung, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 20,
    name: "Bãi đỗ xe tư nhân Cô Năm (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 261, Tỉnh Lộ 8, Xã Tân Thạnh Tây, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 21,
    name: "Bãi đỗ xe Gara Thành Danh (Dự kiến hoạt động từ 31/12/2023)",
    address: "Xã Tân Thạnh Đông, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 22,
    name: "Cửa hàng xăng dầu Dương Trí số 28 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 1544, Tỉnh lộ 8, ấp 4, xã Hòa Phú, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 23,
    name: "Cửa hàng xăng dầu PVOIL NQTM DKMN Số 1 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Hòa Phú, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 24,
    name: "Cửa hàng xăng dầu Sơn Ga 1 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 248, Đường Võ Văn Bích, Xã Bình Mỹ, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 25,
    name: "Cửa hàng xăng dầu PDT NQTM Phương Thủy (Dự kiến hoạt động từ 31/12/2023)",
    address: "Số 209B, Tỉnh lộ 9, Xã Bình Mỹ, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 26,
    name: "Bãi đỗ xe tư nhân Số 36 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Xã Phú Hòa Đông, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 27,
    name: "Bãi đỗ xe tư nhân Cô Nga 4 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Xã Phú Hòa Đông, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 28,
    name: "Bãi đỗ xe tư nhân Cô Nga 1 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Xã Phạm Văn Cội, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 29,
    name: "Bãi đỗ xe tư nhân Chú Út (Dự kiến hoạt động từ 31/12/2023)",
    address: "Xã Phú Hòa Đông, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 30,
    name: "Bãi đỗ xe tư nhân Cô Nga 2 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Xã Nhuận Đức, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 31,
    name: "Bãi đỗ xe tư nhân Cô Nga 3 (Dự kiến hoạt động từ 31/12/2023)",
    address: "Xã An Nhơn Tây, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 32,
    name: "Bãi đỗ xe tư nhân Chú Tâm (Dự kiến hoạt động từ 31/12/2023)",
    address: "Xã An Nhơn Tây, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 33,
    name: "Cửa hàng xăng dầu Petrolimex Hồ Chí Minh Số 66 (Dự kiến hoạt động từ 28/10/2023)",
    address: "Số 1547, Tỉnh lộ 15, Ấp An Hòa, Xã An Phú, Huyện Củ Chi, TP. Hồ Chí Minh",
    district: "Huyện Củ Chi",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];

  export const huyenCanGioStations = [
  {
    id: 1,
    name: "Bãi đỗ xe Nguyễn Thị Cảnh",
    address: "Số 2-22, Đường Duyên Hải, Thị trấn Cần Thạnh, Huyện Cần Giờ, Thành phố Hồ Chí Minh.",
    district: "Huyện Cần Giờ",
    ports: "08 cổng sạc 11Kw, 10 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Bãi đỗ xe tư nhân Nguyễn Mạnh Hà - Cần Giờ",
    address: "Số 204-206, đường Duyên Hải, Thị trấn Cần Thạnh, Huyện Cần Giờ, Thành phố Hồ Chí Minh.",
    district: "Huyện Cần Giờ",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Cửa hàng xăng dầu TLP NQTM Đức Thanh",
    address: "Số 166, Đường Duyên Hải, Ấp Long Thạnh, Xã Long Hòa, Huyện Cần Giờ, Thành phố Hồ Chí Minh.",
    district: "Huyện Cần Giờ",
    ports: "01 cổng sạc 250Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Cửa hàng xăng dầu Châu Văn Vân",
    address: "Xã Lý Nhơn, Huyện Cần Giờ, Thành phố Hồ Chí Minh.",
    district: "Huyện Cần Giờ",
    ports: "02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Cửa hàng xăng dầu Phát Tài",
    address: "Số 108, đường Rừng Sác, ấp An Nghĩa, xã An Thới Đông, Huyện Cần Giờ, Thành phố Hồ Chí Minh.",
    district: "Huyện Cần Giờ",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "Cửa hàng xăng dầu Petrolimex Hồ Chí Minh Số 69",
    address: "Số 586, đường Rừng Sác, ấp Bình An, xã Bình Khánh, Huyện Cần Giờ, Thành phố Hồ Chí Minh.",
    district: "Huyện Cần Giờ",
    ports: "02 cổng sạc 180Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Cửa hàng xăng dầu Phú Thịnh",
    address: "Số 101, đường Rừng Sác, xã Bình Khánh, Huyện Cần Giờ, Thành phố Hồ Chí Minh.",
    district: "Huyện Cần Giờ",
    ports: "02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "TTTM Co.op Mart Cần Giờ",
    address: "128 Đào Cử, TT. Cần Thạnh, Cần Giờ, Hồ Chí Minh.",
    district: "Huyện Cần Giờ",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "Bãi đỗ xe tư nhân Tam Thôn Hiệp",
    address: "Huyện Cần Giờ, Thành phố Hồ Chí Minh.",
    district: "Huyện Cần Giờ",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];

export const huyenBinhChanhStations = [
  {
    id: 1,
    name: "Nhượng quyền Luxury - Hộ kinh doanh Kim Dung",
    address: "2511, QL50, Đa Phước, Huyện Bình Chánh, Huyện Bình Chánh, Thành phố Hồ Chí Minh",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 60Kw, 04 cổng sạc 120Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Bãi đỗ xe tư nhân Anh Dũng 2",
    address: "Số 493, Hương Lộ 11, Xã Hưng Long, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Nhượng quyền Luxury - Công ty Garage Thành Công",
    address: "Số 36, Đường 13, Khu dân cư Phong Phú, Xã Phong Phú, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Bãi đỗ xe tư nhân XTS 36",
    address: "39 Trịnh Như Khuê, Huyện Bình Chánh, Thành phố Trung ương Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Bãi đỗ xe tư nhân Phong Phú Bình Hưng",
    address: "Thửa đất 565;566;567 tờ bản đồ 114, xã Bình Hưng, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "Nhượng quyền Tư nhân - Nguyễn Thị Thùy Linh",
    address: "31 đường 23 KDC Phong Phú 5, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "01 cổng sạc 22Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Bãi đỗ xe Phong Phú",
    address: "Thửa đất số 888, tờ bản đồ số 4, xã Phong Phú, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 22Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "Bãi đỗ xe Anh Vũ",
    address: "Xã Tân Kiên, Huyện Bình Chánh, Thành phố Hồ Chí Minh",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "Bãi đỗ xe tư nhân Tân Nhựt",
    address: "B10/2023B, Ấp 2, Xã Tân Nhựt, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 10,
    name: "Bãi đỗ xe tư nhân Đa Phước",
    address: "Xã Đa Phước, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 11,
    name: "Bãi đỗ xe tư nhân Láng Le Bàu Cò",
    address: "Láng Le Bàu Cò, Xã Tân Nhựt, Huyện Bình Chánh, Thành phố Hồ Chí Minh",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 12,
    name: "Bãi đỗ xe tư nhân Thiên Ân 8",
    address: "G1/8, Ấp 7, xã Lê Minh Xuân, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 13,
    name: "TTTM Co.op Mart Vĩnh Lộc B",
    address: "2 Đường số 8, Khu tái định cư, Bình Chánh, Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 14,
    name: "Bãi đỗ xe tư nhân Trần Văn Giàu",
    address: "Xã Lê Minh Xuân, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "06 cổng sạc 11Kw, 10 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 15,
    name: "Nhượng quyền Standard - Hộ kinh doanh Phạm Thị Mai Anh",
    address: "F5/35C, Ấp 6, Xã Lê Xuân Minh, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 120Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 16,
    name: "Bãi đỗ xe tư nhân Anh Nguyện 2",
    address: "D20/9X, Ấp 4A, Xã Vĩnh Lộc A, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "06 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 17,
    name: "Bãi đỗ xe tư nhân Vĩnh Lộc",
    address: "Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 18,
    name: "Bãi đỗ xe tư nhân Liên Ấp",
    address: "Số 434, Đường Liên ấp 2- 6, Xã Vĩnh Lộc A, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 19,
    name: "Nhượng quyền TXTX - Nguyễn Phú Cường",
    address: "Số 122 ấp 2, Đường liên ấp 234, Xã Vĩnh Lộc A, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "01 cổng sạc 22Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 20,
    name: "Bãi đỗ xe tư nhân Thới Hòa",
    address: "E1/6, Đường Thới Hòa, Ấp 5, Xã Vĩnh Lộc A, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "05 cổng sạc 11Kw, 10 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 21,
    name: "Bãi đỗ xe Anh Minh",
    address: "Xã Phạm Văn Hai, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 11Kw, 08 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 22,
    name: "Cửa hàng xăng dầu An Hạ",
    address: "Số 6, Đường An Hạ, Xã Phạm Văn Hai, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 23,
    name: "Bãi đỗ xe tư nhân 33 Phạm Văn Sáng",
    address: "Số 33, Đường Phạm Văn Sáng, Xã Vĩnh Lộc A, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "01 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 24,
    name: "Cửa hàng xăng dầu Mỹ Anh 2",
    address: "Đường tỉnh 825, Phường Bình Lợi, Huyện Bình Chánh, Thành phố Hồ Chí Minh",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 180Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 25,
    name: "Cửa hàng xăng dầu Petrolimex Hồ Chí Minh Số 62",
    address: "Số 3A52/1, Tỉnh lộ 10, Ấp 3, xã Phạm Văn Hai, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 180Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 26,
    name: "Bãi đỗ xe công ty AZC 1",
    address: "Số 2A6,7 Đường Tỉnh Lộ 10, Xã Phạm Văn Hai, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "10 cổng sạc 11Kw, 10 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 27,
    name: "Bãi đỗ xe Hoàng Nha Coffee",
    address: "Số 1742, đường Trần Văn Giàu, Ấp 1, xã Phạm Văn Hai, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "01 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 28,
    name: "Bãi đỗ xe Cường Phát",
    address: "Số B11/29, Ấp 2, Xã Vĩnh Lộc B, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 29,
    name: "Bãi đỗ xe 24/24 Võ Văn Vân",
    address: "A3/9 Ấp 1, xã Vĩnh Lộc B, Huyện Bình Chánh, Thành phố Hồ Chí Minh",
    district: "Huyện Bình Chánh",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 30,
    name: "Bãi đỗ xe Gara Lữ Dũng",
    address: "A5/12F1, Ấp 1A, xã Vĩnh Lộc B, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 31,
    name: "Bãi đỗ xe Thuận An Khang",
    address: "Số B7/15D, đường Nguyễn Hữu Trí, Khu phố 2, Thị Trấn Tân Túc, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 11Kw, 08 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 32,
    name: "Bãi đỗ xe tư nhân Hoàng Phan Thái",
    address: "Xã Bình Chánh, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 33,
    name: "Trạm dừng nghỉ Bờ Nhà Thờ",
    address: "Số 24, đường Bờ Nhà Thờ, Xã Bình Chánh, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 11Kw, 10 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 34,
    name: "Cửa hàng xăng dầu Tuyết Anh 2",
    address: "D14/6A, Đường Thế Lữ, Huyện Bình Chánh, Thành phố Hồ Chí Minh",
    district: "Huyện Bình Chánh",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 35,
    name: "Bãi đỗ xe KDC Tân Túc",
    address: "Thị trấn Tân Túc, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "04 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 36,
    name: "Bãi đỗ xe 83 Bùi Thanh Kiết",
    address: "Số 83, đường Bùi Thanh Khiết, Thị trấn Tân Túc, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 37,
    name: "Gara Thành Công",
    address: "Số 42, Đường số 13, Ấp 5, Xã Phong Phú, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "04 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 38,
    name: "Bãi đỗ xe Sân Công long Tam Anh",
    address: "Số E9/251E, Ấp 5, Xã Phong Phú, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 39,
    name: "Bãi đỗ xe Ngoài trời Chung cư Terra Mi-A - Bình Chánh",
    address: "Lô số 8, Khu 6B, Khu chức năng số 6, Đô thị mới Nam Thành Phố, Xã Bình Hưng, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 40,
    name: "Cửa hàng xăng dầu Petrolimex Hồ Chí Minh Số 56",
    address: "Số A8/233A, Quốc lộ 50, Ấp 1, Xã Đa Phước, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "02 cổng sạc 150Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 41,
    name: "Cửa hàng xăng dầu Hoàng Thái",
    address: "Số D8/1A, ấp 4, Quốc Lộ 50, xã Quy Đức, Huyện Bình Chánh, Thành phố Hồ Chí Minh",
    district: "Huyện Bình Chánh",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 42,
    name: "Cửa hàng xăng dầu PVOIL SG số 19 ( Cửa hàng xăng dầu số 1)",
    address: "Số 4A-164, Đường Thanh Niên, Xã Phạm Văn Hai, Huyện Bình Chánh, Thành phố Hồ Chí Minh.",
    district: "Huyện Bình Chánh",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
];
export const CHARGING_STATIONS: ChargingStation[] = [
  // Thành phố Thủ Đức
  {
    id: 1,
    name: "Trạm sạc VinFast Bãi đỗ xe Nguyễn Văn Út",
    address: "351/2 Lê Văn Thịnh nối dài, Phường Cát Lái, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân Cô Năm",
    address: "Số 59, Đường 26, Khu phố 2, Phường Cát Lái, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Trạm sạc VinFast Chung cư Centana",
    address: "Số 36, Đường Mai Chí Thọ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "6 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Trạm sạc VinFast Công ty cổ phần thương mại dịch vụ kỹ thuật Phúc Sang Minh",
    address: "Số 3, đường 43 khu nhà ở An Phú- Mỹ Mỹ, KP5, P.An Phú, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Trạm sạc VinFast Bãi đỗ xe Chung Cư PetroVietnam Landmark",
    address: "Thành phố Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "Trạm sạc VinFast MM Mega Market An Phú",
    address: "Thành phố Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Trạm sạc VinFast Vincom Mega Mall Thảo Điền, bên trái TTTM",
    address: "Bãi đỗ xe ngoài trời, bên trái Vincom Mega Mall Thảo Điền, số 161, đường Xa lộ Hà Nội, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "14 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "Trạm sạc VinFast Vincom Mega Mall Thảo Điền, hầm B2",
    address: "Trong bãi TGX tầng B2 cho xe máy và tầng B3 cho xe ô tô Vincom Mega Mall Thảo Điền, số 161, đường Xa lộ Hà Nội, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "54 cổng sạc 60Kw, 12 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "Trạm sạc VinFast Vincom Mega Mall Thảo Điền - Trong hầm",
    address: "Số 161, đường Xa lộ Hà Nội, phường Thảo Điền, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
    district: "Thành phố Thủ Đức",
    ports: "08 cổng sạc 60Kw, 01 cổng sạc 11Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 10,
    name: "Trạm sạc VinFast Đại lý Ô tô VinFast Đông Sài Gòn",
    address: "Số 391, Xa Lộ Hà Nội, Phường An Phú, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 80Kw, 02 cổng sạc 120Kw, 04 cổng sạc 60Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 11,
    name: "Trạm sạc VinFast Nhượng quyền - Văn phòng Phú Long - Dragon Village",
    address: "Thành phố Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 12,
    name: "Trạm sạc VinFast Bãi đỗ xe Phú Hữu",
    address: "Phường Phú Hữu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 13,
    name: "Trạm sạc VinFast Bãi đỗ xe 882",
    address: "Đường 882, Phường Phú Hữu, Thủ đức, Hcm, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 14,
    name: "Trạm sạc VinFast Bãi đỗ xe công ty AZC 3",
    address: "Số 240, đường Võ Chí Công, Phường Phú Hữu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "10 cổng sạc 11Kw, 10 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 15,
    name: "Trạm sạc VinFast Bãi đỗ xe Eco City – Bình Trưng Đông",
    address: "Dự án Khu nhà ở tại Phường Bình Trưng Đông, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 16,
    name: "Trạm sạc VinFast Cafe Sông Trăng",
    address: "Số 711, đường Đỗ Xuân Hợp, Phường Phú Hữu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 17,
    name: "Trạm sạc VinFast Bãi đỗ xe Khu dân cư Đại Học Bách Khoa",
    address: "Đường 711A, Phường Phú Hữu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw, 12 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 18,
    name: "Trạm sạc VinFast Bãi đỗ xe Gara AUTO 666",
    address: "Số 681/1, Đường Đỗ Xuân Hợp, Phường Phước Long B, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 19,
    name: "Trạm sạc VinFast Gara Linh Vy Auto",
    address: "Số 01, Huy Cận, Khu dân cư Gia Hòa. phường Phước Long B, TP Thủ Đức, Hcm., Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 20,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân D3B",
    address: "Đường D3B, Phường Phước Long B, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 11Kw, 08 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 21,
    name: "Trạm sạc VinFast Chung cư Sky 9, CT1",
    address: "CT1 chung cư Sky 9, 61-63 đường số 1, khu phố 2, phường Phú Hữu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 22,
    name: "Trạm sạc VinFast Chung cư Sky 9, hầm B1- CT3",
    address: "Tầng hầm B1 - CT3, Chung cư Sky 9, Số 61-63, đường số 1, khu phố 2, phường Phú Hữu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 23,
    name: "Trạm sạc VinFast Cửa hàng xăng dầu PVOIL Phú Hữu, Thủ Đức",
    address: "Số 579, đường Võ Chí Công, Phường Phú Hữu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 180Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 24,
    name: "Trạm sạc VinFast Chung cư The Eastern",
    address: "Chung cư The Eastern, 299 đường Liên phường, phường Phú Hữu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 25,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân Bưng Ông Thoàn",
    address: "Số 144. Đường Bưng Ông Thoàn, Phường Phú Hữu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 22Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 26,
    name: "Trạm sạc VinFast Cửa hàng xăng dầu PVOIL TI Long Trường",
    address: "Long Trường, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 180Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 27,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân Long Trường",
    address: "Số 1426/16, đường Nguyễn Duy Trinh, phường Long Trường, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "05 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 28,
    name: "Trạm sạc VinFast Cửa hàng xăng dầu Long Trường",
    address: "Số 766, Đường Lã Xuân Oai, Phường Long Trường, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 29,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân Tam Đa",
    address: "48 đường Tam Đa, phường Long Trường, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 30,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân Đông Thăng Long",
    address: "Phường Trường Thạnh, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw, 04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 31,
    name: "Trạm sạc VinFast Bãi đỗ xe 9/1 Võ Văn Hát",
    address: "9/1 Võ Văn Hát, Phường Long Trường, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 32,
    name: "Trạm sạc VinFast Cửa hàng xăng dầu Số 1 Lò Lu",
    address: "2H Đường Lò Lu, Trường Thạnh, Thành phố Thủ Đức, Thành phố Trung ương Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 33,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân 322 Long Thuận",
    address: "Số 322, Đường Long Thuận, Phường Long Phước, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "05 cổng sạc 11Kw, 12 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 34,
    name: "Trạm sạc VinFast Vinhomes Grand Park, khu 12",
    address: "Số 512 Nguyễn Xiễn, khu phố Long Hòa, phường Long Thạnh Mỹ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "01 cổng sạc 11Kw, 26 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 35,
    name: "Trạm sạc VinFast Vinhomes Grand Park, khu 10",
    address: "Số 512 Nguyễn Xiễn, khu phố Long Hòa, phường Long Thạnh Mỹ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 11Kw, 54 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 36,
    name: "Trạm sạc VinFast Vinhomes Grand Park - Thương mại dịch vụ Broadway",
    address: "Đường Nguyễn Xiển, Phường Long Thạnh Mỹ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "12 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 37,
    name: "Trạm sạc VinFast Vinhomes Grand Park VP 43 tầng",
    address: "Thành phố Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 38,
    name: "Trạm sạc VinFast Chung cư Vinhomes Grand Park 3 ,Tòa S3",
    address: "Tầng hầm B2,Tòa S3 Vinhomes Grand Park Nguyễn Xiển, phường Long Thạnh Mỹ, Thành phố Thủ Đức, Thành phố Trung ương Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 39,
    name: "Trạm sạc VinFast Chung cư Vinhomes Grand Park 4, Tòa S5",
    address: "Tầng hầm B2 Tòa S5 Vinhomes Grand Park Nguyễn Xiển, phường Long Thạnh Mỹ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 40,
    name: "Trạm sạc VinFast Vinhomes Grand Park, khu 7",
    address: "Số 512 Nguyễn Xiễn, khu phố Long Hòa, phường Long Thạnh Mỹ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "14 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 41,
    name: "Trạm sạc VinFast Chung cư Vinhomes Grand Park,Tòa S1",
    address: "Tầng hầm B2, Tòa S1 Vinhomes Grand Park Nguyễn Xiển, phường Long Thạnh Mỹ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 42,
    name: "Trạm sạc VinFast Chung cư Vinhomes và Grand Park 1, Tòa S2",
    address: "Tầng hầm B2 Tòa S2 Vinhomes Grand Park Nguyễn Xiển, phường Long Thạnh Mỹ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 43,
    name: "Trạm sạc VinFast Vinhomes Grand Park, khu 4,Tòa S7.02",
    address: "Số 512 Nguyễn Xiển, Tổ Dân phố 16, Khu phố Long Hòa, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "08 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 44,
    name: "Trạm sạc VinFast Vinhomes Grand Park, khu 5 ,Tòa S8",
    address: "Số 512 Nguyễn Xiển, Tổ Dân phố 16, Khu phố Long Hòa, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 45,
    name: "Trạm sạc VinFast Vinhomes Grand Park, khu 6, Tòa S9",
    address: "Số 512 Nguyễn Xiển, Tổ Dân phố 16, Khu phố Long Hòa, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "06 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 46,
    name: "Trạm sạc VinFast Vinhomes Grand Park, khu 3, Tòa S6",
    address: "số 512 Nguyễn Xiển, Tổ Dân phố 16, Khu phố Long Hòa, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "09 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 47,
    name: "Trạm sạc VinFast Vinhomes Grand Park, khu 2,Tòa S10.07",
    address: "số 512 Nguyễn Xiển, Tổ Dân phố 16, Khu phố Long Hòa, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 48,
    name: "Trạm sạc VinFast Vinhomes Grand Park, khu 1, Tòa S10.05",
    address: "số 512 Nguyễn Xiển, Tổ Dân phố 16, Khu phố Long Hòa, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 49,
    name: "Trạm sạc VinFast Vinhomes Grand Park, hầm B2- Tòa S1",
    address: "Hầm B2-S1-PK1, Vinhomes Grand Park, đường Nguyễn Xiển, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "32 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 50,
    name: "Trạm sạc VinFast Vinhomes Grand Park, hầm B2-Tòa S2",
    address: "Hầm B2-S2-PK1, Vinhomes Grand Park, đường Nguyễn Xiển, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "30 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 51,
    name: "Trạm sạc VinFast Vinhomes Grand Park, hầm B2-Tòa S3",
    address: "Hầm B2-S3-PK1, Vinhomes Grand Park, đường Nguyễn Xiển, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "22 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 52,
    name: "Trạm sạc VinFast Vinhomes Grand Park, hầm B2-Tòa S5",
    address: "Hầm B2-S5, Vinhomes Grand Park, đường Nguyễn Xiển, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "14 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 53,
    name: "Trạm sạc VinFast Vinhomes Grand Park - Lô B1, Phân khu 3",
    address: "Phường Long Bình, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "21 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 54,
    name: "Trạm sạc VinFast Nhượng quyền - Vinhomes Grand Park Depot Vinbus",
    address: "Phường Long Thạnh Mỹ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh",
    district: "Thành phố Thủ Đức",
    ports: "06 cổng sạc 180Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 55,
    name: "Trạm sạc VinFast Vinhomes Grand Park PK3 Hầm B2-Tòa BS12-PK3",
    address: "Phường Long Bình, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "88 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 56,
    name: "Trạm sạc VinFast Vinhomes Grand Park- Khu 8",
    address: "Phường Long Bình, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 57,
    name: "Trạm sạc VinFast Vinhomes Grand Park Bãi đỗ xe P02",
    address: "Thành phố Thủ Đức, Thành phố Trung ương Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 58,
    name: "Trạm sạc VinFast Vinhomes Grand Park - Lô B4, Phân khu 4",
    address: "Phường Long Bình, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "26 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 59,
    name: "Trạm sạc VinFast Bãi đỗ xe Nguyễn Xiển",
    address: "Số 979, Đường Nguyễn Xiển, Phường Long Bình, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 60,
    name: "Trạm sạc VinFast Khách Sạn Little Sài Gòn - Thủ Đức",
    address: "27 đường 11, P Long Bình, Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 61,
    name: "Trạm sạc VinFast Bãi đỗ xe Trạm xe dịch vụ Bệnh viện Ung Bướu",
    address: "27 đường 11, P Long Bình, Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "09 cổng sạc 11Kw, 16 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 62,
    name: "Trạm sạc VinFast Nhượng quyền - Văn phòng HDBank Khu Công nghệ cao Thủ Đức",
    address: "Thành phố Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 63,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân A74",
    address: "Số 491/2 Xa lộ Hà Nội, Phường Linh Trung, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 11Kw, 06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 64,
    name: "Trạm sạc VinFast Bãi đỗ xe Co-op Xtra Linh Trung",
    address: "Số 934, Quốc lộ 1A, Phường Linh Trung, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 65,
    name: "Trạm sạc VinFast Bãi đỗ xe Linh Xuân - Thủ Đức",
    address: "222A, đường số 8, Phường Linh Xuân, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 11Kw, 06 cổng sạc 80Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 66,
    name: "Trạm sạc VinFast Bệnh viện Đa khoa Quốc tế Hoàn Mỹ Thủ Đức",
    address: "Số 241, Quốc lộ 1K, phường Linh Xuân, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 67,
    name: "Trạm sạc VinFast Bãi đỗ xe Anh Quốc",
    address: "Số 25/13, Đường số 6, Khu phố 3, phường Tăng Nhơn Phú B, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 68,
    name: "Trạm sạc VinFast Nhượng quyền - Bãi đỗ xe tư nhân Tăng Nhơn Phú",
    address: "Thành phố Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 69,
    name: "Trạm sạc VinFast Vincom Plaza Lê Văn Việt, phía sau TTTM",
    address: "Bãi đỗ xe ngoài trời, phía sau Vincom Plaza Lê Văn Việt, số 50, đường Lê Văn Việt, Thành phố Thủ Đức, Thành phố Trung ương Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "06 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 70,
    name: "Trạm sạc VinFast Vincom Plaza Lê Văn Việt-Trước sảnh TTTM",
    address: "Bãi đỗ xe ngoài trời, mặt tiền Vincom Plaza Lê Văn Việt, số 50, đường Lê Văn Việt, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "12 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 71,
    name: "Trạm sạc VinFastVincom Plaza Lê Văn Việt, hầm B1",
    address: "Hầm B1, Vincom Plaza Lê Văn Việt, số 50, đường Lê Văn Việt, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 72,
    name: "Trạm sạc VinFast Vincom Plaza Lê Văn Việt - Trong hầm",
    address: "Tầng hầm Vincom Lê Văn Việt Số 50, đường Lê Văn Việt, phường Hiệp Phú, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 73,
    name: "Trạm sạc VinFast Bãi đỗ xe 26C Phan Chu Trinh",
    address: "Số 26C, đường Phan Chu Trinh, Phường Hiệp Phú, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 74,
    name: "Trạm sạc VinFast Cửa hàng xăng dầu PVOIL Bình Thọ",
    address: "Đường Nguyễn Văn Bá, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 75,
    name: "Trạm sạc VinFast Nhượng quyền TXTX - Hoàng Ngọc Hải",
    address: "Số 29/48, Đường số 4, Khu phố 6, Phường Trường Thọ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 22Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 76,
    name: "Trạm sạc VinFast Nhượng quyền Luxury - Công ty Minh Mẫn",
    address: "Thành phố Thủ Đức, Thành phố Thủ Đức, Thành phố Trung ương Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 77,
    name: "Trạm sạc VinFast Bãi đỗ xe Eco City - Trường Thọ",
    address: "Số 13-15, Đường số 2, Khu phố 9, Phường Trường Thọ, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 78,
    name: "Trạm sạc VinFast Bãi đỗ xe Anh Sơn",
    address: "28 đường 11 phường Bình Thọ, Q Thủ Đức, Hcm, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "06 cổng sạc 11Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 79,
    name: "Trạm sạc VinFast Bãi đỗ xe Linh Đông",
    address: "Số 132, đường Linh Đông, Khu phố 4, phường Linh Đông, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 80,
    name: "Trạm sạc VinFast Vincom Plaza Thủ Đức, hầm B1",
    address: "Tầng Hầm Vincom Plaza Thủ Đức, số 216, đường Võ Văn Ngân, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "08 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 81,
    name: "Trạm sạc VinFast Vincom Plaza Thủ Đức - Hầm B1",
    address: "Số 132, đường Linh Đông, Khu phố 4, phường Linh Đông, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "04 cổng sạc 60Kw, 02 cổng sạc 11Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 82,
    name: "Trạm sạc VinFast Bãi đỗ xe Khu dân cư ARECO",
    address: "Lô A82-A83, Khu dân cư Areco, Phường Linh Tây, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 83,
    name: "Trạm sạc VinFast Bãi đỗ xe Hoàng Sơn",
    address: "Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "03 cổng sạc 22Kw, 10 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 84,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân Gò Dưa 76",
    address: "Số 49, Đường số 11, Phường Tam Bình, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 85,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân Ngô Chí Quốc",
    address: "Phường Bình Chiểu, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 86,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân Bình Chiều",
    address: "Thửa đất số 526, tờ bản đồ số 49 tại phường Bình Chiều, quận Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 87,
    name: "Trạm sạc VinFast Bãi đỗ xe Sao Vàng",
    address: "Số 13, Đường số 8, Khu phố 4, Phường Hiệp Bình Phước, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 88,
    name: "Trạm sạc VinFast Bãi đỗ xe Hợp tác xã Quốc Bảo",
    address: "Số 48/2, Đường 40, Khu phố 25, phường Hiệp Bình Chánh, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 89,
    name: "Trạm sạc VinFast Cửa hàng xăng dầu số 2",
    address: "Số 778, Đường Phạm Văn Đồng, Phường Hiệp Bình Chánh, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 90,
    name: "Trạm sạc VinFast Bãi đỗ xe tư nhân Đường số 19",
    address: "Thửa đất số 606, Tờ bản đồ số 141, phường Hiệp Bình Chánh, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 91,
    name: "Trạm sạc VinFast TTTM Co.op Mart Bình Triệu",
    address: "Thành phố Thủ Đức, Thành phố Thủ Đức, Thành phố Hồ Chí Minh.",
    district: "Thành phố Thủ Đức",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  // Quận 1
  {
    id: 1,
    name: "Bãi đỗ xe Công ty SAFi",
    address: "Số 209, đường Nguyễn Văn Thủ, Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 2,
    name: "Tòa nhà SFC",
    address: "Số 9, đường Đinh Tiên Hoàng, phường Đa Kao, Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "01 cổng sạc 11Kw, 02 cổng sạc 60Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 3,
    name: "Vinhomes Golden River, hầm B3, khu 2",
    address: "Hầm B3 Vinhomes Golden River, số 2, đường Tôn Đức Thắng, Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 4,
    name: "Chung cư Vinhomes Golden River 1",
    address: "Tòa AQUA 3, Hầm B3, số 2 đường Tôn Đức Thắng, phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 5,
    name: "Chung cư Vinhomes Golden River 2",
    address: "Tòa LUXURY 6, Hầm B3, số 2 đường Tôn Đức Thắng, phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "03 cổng sạc 11Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 6,
    name: "Vincom Center Đồng Khởi - Hầm B5",
    address: "Hầm B5, số 72, đường Lê Thánh Tôn, phường Bến Nghé, Quận 1, TP. Hồ Chí Minh.",
    district: "Quận 1",
    ports: "02 cổng sạc 11Kw, 04 cổng sạc 60Kw, 02 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 7,
    name: "Vincom Center Đồng Khởi, Hầm B6",
    address: "Hầm B6, Vincom Center Đồng Khởi, số 72, đường Lê Thánh Tôn, phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "24 cổng sạc 60Kw, 09 cổng sạc 30Kw",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 8,
    name: "Bãi đỗ xe Sở Giao Thông Vận Tải Hồ Chí Minh",
    address: "Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 9,
    name: "Nhượng quyền - Văn phòng HD Bank Hội sở",
    address: "Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 10,
    name: "Vinhomes Golden River, hầm B2, khu 1",
    address: "Hầm B2 Vinhomes Golden River, số 2, đường Tôn Đức Thắng, Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  {
    id: 11,
    name: "Vinhomes Golden River, hầm B2, khu 2",
    address: "Hầm B2, Vinhomes Golden River, số 2, đường Tôn Đức Thắng, Quận 1, Thành phố Hồ Chí Minh.",
    district: "Quận 1",
    ports: "Đang cập nhật",
    latitude: 0,
    longitude: 0,
    mapX: 0,
    mapY: 0,
  },
  ...quan3Stations,
  ...quan4Stations,
  ...quan5Stations,
  ...quan6Stations,
  ...quan7Stations,
  ...quan8Stations,
  ...quan10Stations,
  ...quan11Stations,
  ...quan12Stations,
  ...huyenNhaBeStations,
  ...huyenHocMonStations,
  ...huyenCuChiStations,
  ...huyenCanGioStations,
  ...huyenBinhChanhStations,
];
  // 


// Calculate map coordinates for all stations
export const STATIONS_WITH_COORDS = CHARGING_STATIONS.map((station) => ({
  ...station,
  mapX: lngToX(station.longitude),
  mapY: latToY(station.latitude),
}));

// Group stations by district
export const STATIONS_BY_DISTRICT = STATIONS_WITH_COORDS.reduce(
  (acc, station) => {
    if (!acc[station.district]) {
      acc[station.district] = [];
    }
    acc[station.district].push(station);
    return acc;
  },
  {} as Record<string, ChargingStation[]>
);

export const DISTRICTS = Object.keys(STATIONS_BY_DISTRICT).sort();
